### ISSUE TITLE
Tracking issue for new release

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly-games#104]
This bug is to keep track of issues involving the next release of Blockly Games.  This is a fairly light-weight release, with most of the problems originating from changes to the Blockly codebase.

Main features:
* Insertion markers when connecting blocks.
* Four new languages: Basque, Armenian, Interlingua, Urdu.
* Movie level two was [missing a block](https://github.com/google/blockly-games/issues/100) in toolbox.
* [Dialog issues](https://github.com/google/blockly-games/issues/101) in JS levels of Pond (possibly only in uncompiled mode?).

Upstream Blockly issues:
- [x] https://github.com/google/blockly/issues/2217 Insertion markers strobe when snap radius is increased.
- [x] https://github.com/google/blockly/issues/2216 Maximum Block Limit demo off by one.
- [x] https://github.com/google/blockly/issues/2215 Colours on advanced compilation demos are all black.
- [x] https://github.com/google/blockly/issues/2236 workspace.getAllBlocks shouldn't return insertion markers by default.
- [x] https://github.com/google/blockly/issues/2277 Mutators appear under toolbox

Blockly Games issues:
- *none*

**Comment by NeilFraser** [comment]
Pushing new version now...
