### ISSUE TITLE
Tracking issue for new release

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly-games#118]
Upstream Blockly issues:
- [ ] https://github.com/google/blockly/issues/3245 Angle picker still live while disappearing
- [ ] https://github.com/google/blockly/issues/3243 Trashcan duplicates disabled blocks when maxBlocks is hit
- [ ] https://github.com/google/blockly/issues/3077 Prevent blocks from toggling inline/external

**Comment by olavurellefsen** [comment]
Can you enable the Faroese language ('fo') in this release? Translation is complete.

**Comment by NeilFraser** [comment]
@olavurellefsen Awesome!  Added via https://github.com/google/blockly-games/commit/aed80aaa5789121874e80a2de6d7ebf8c0478eb8

Will rebuild overnight and (assuming the build tests out properly) push to production on Friday.

**Comment by NeilFraser** [comment]
@olavurellefsen Now live: https://blockly.games/?lang=fo

I made some small corrections to a handful of translations where a word is a JavaScript function name and should not have been translated: https://github.com/google/blockly-games/commit/750fa282849bc5e437ef239f3bd6666c98112d54
