### ISSUE TITLE
Migration Tracking Bug

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly-games#245]
The move from App Engine to a dedicated server went well.  However, there's a number of long tail items to deal with:

- [ ] Get port 8000 working for admin.
- [ ] Setup AWStats and remove Google Analytics.
- [ ] Initiate Security test as promised.
- [ ] Initiate Legal review as promised.
- [ ] Cache Gallery entries for faster loading.
- [ ] Create HTTP redirects using latest App Engine version.
- [ ] Investigate non-XML non-JS save file entries.
