### ISSUE TITLE
Tracking issue for release

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly-games#71]
This bug is to keep track of issues involving the next release of Blockly Games.  The last release was pushed 28 June 2016, so this one is *long* overdue.

Staging URL:  https://beta-dot-blockly-games.appspot.com/

Main features:
* Music game that teaches functions.
* New levels for movie game.
* Internal gallery, replacing Reddit.
* New translations, including Kabyle: https://github.com/google/blockly-games/issues/66
* Separate execution highlighting from selection highlighting.

Upstream Blockly issues:
- [x] https://github.com/google/blockly/issues/1810 Category selected UI event has null element.
- [x] https://github.com/google/blockly/issues/1425 Mutators in FF are broken in RTL.
- [x] https://github.com/google/blockly/issues/503 (probably the same as https://github.com/google/blockly/issues/772) Functions called "do something" don't survive round-tripping to XML.
- [x] https://github.com/ajaxorg/ace-builds/issues/123 package 31.01.18 doesn't contain latest code.
- [x] https://github.com/google/blockly/issues/1699 Blockly.Mutator.findParentWs is @package
- [x] https://github.com/google/blockly/issues/1726 Blockly.un/bindEvent_ is @package

Blockly Games issues:
- *none*

**Comment by NeilFraser** [comment]
Release pushed!
